---
title: "vis_eda_part1"
output: github_document
---

```{r packages}
library(tidyverse)
library(ggridges)
```

## Load in a dataset that we'll use

```{r }
weather_df <- 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatterplot

tmax v.s. tmin

```{r }
ggp_tmax_tmin <-
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
# you can save plot
ggp_tmax_tmin
##ggsave()
```

# Let's fancy it up

color? lines? other?

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name))
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  # color/category needs to be in the first feature mapping code
  # can update the category setting in geometry geom_smooth(color = NULL, se = FALSE)
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```
Let's make more scatterplot
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .3) +
  # se gives standard error areas
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

```
## Use data manipulation as part of this

```{r}
weather_df %>%
  filter(name == "CentralPark_NY") %>%
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32
  ) %>%
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)
```
## Stacking geom

Which geom do you want

```{r}
# Showing only the lines
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  # se gives standard error areas
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```
## Univaraite plots

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(.~ name)
```
Let's try other plots
```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)
```

Still with `tmin` and `tmax`
```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

Some people like violin box
```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```
What about ridges ...

```{r}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```






